/*******CARGA DE DATOS DE SPRING*******/

CREATE TABLE cursoangular.users (
	id INTEGER,
	name VARCHAR,
	email VARCHAR,
	password VARCHAR,
	remember_token VARCHAR,
	created_at TIMESTAMP,
	updated_at TIMESTAMP
) ;

CREATE SEQUENCE IF NOT EXISTS cursoangular.seq_images;
/*CREATE SEQUENCE IF NOT EXISTS cursoangular.HIBERNATE_SEQUENCE;*/


CREATE TABLE cursoangular.images (
	id BIGINT DEFAULT (NEXT VALUE FOR cursoangular.seq_images) not null primary key,
	title VARCHAR,
	description VARCHAR (1250),
	thumbnail VARCHAR,
	imageLink VARCHAR,
	user_id INT,
	created_at TIMESTAMP,
	updated_at TIMESTAMP
) ;

/***************** poblamiento tabla images **************/
/***************** añadido el 19-12-2017 *****************/
INSERT INTO cursoangular.images (title,description,thumbnail,imageLink,user_id,created_at,updated_at) VALUES 
('Dolorem et repellendus praesentium nihil.','Vel a commodi et unde explicabo dolore veniam odio. Dignissimos nam ipsam illo veniam minima sunt natus fugit. Sunt minima accusantium quo officia aut voluptatum harum. Repudiandae praesentium consequatur aut natus fugiat distinctio. Explicabo placeat distinctio dolor est laborum ipsa molestias. Eum voluptatem dolores dolor voluptas suscipit qui quia. Vitae rem voluptatem omnis nemo dolorem. In ipsum rerum minus et. Et quos et enim consectetur reiciendis sit. Possimus reprehenderit reprehenderit facilis alias. Magnam et et suscipit sed explicabo cum velit. Et vitae eaque nesciunt. Est porro odit dolorem in. Est debitis et rerum quidem rem sint sapiente. Quo rerum ad et similique. Qui placeat qui aut ratione cum. Repellat in sapiente voluptatem quia accusamus alias nihil. Numquam et id excepturi autem unde. Delectus enim voluptatem iste nostrum placeat. Neque modi sunt maxime est laboriosam consequuntur. Ut totam architecto cumque est eos id hic. Ut qui incidunt officia maxime.','https://videotutoriales.com/maspa/maspa1.jpg','https://videotutoriales.com/maspa/maspa1-1.jpg',5,'2017-09-21 16:20:52.000','2017-09-21 16:20:52.000')
,('Id non iusto iure sunt nemo occaecati.','Aut ipsum ratione qui mollitia quis. Laboriosam enim placeat consectetur reprehenderit quisquam qui. Vero aut minima aliquid nemo sint. Numquam aliquam debitis molestiae maiores porro distinctio. Voluptatem in aut vel tenetur impedit. Et autem iure culpa rerum provident aut. Ullam quo officia quae unde est. Consequatur repellendus et voluptates eveniet doloremque. Quo et dolorem vel in culpa ea. Nemo sequi nisi soluta autem. Ut adipisci adipisci unde ut. Aut voluptatum ut qui ab nihil et. Nobis voluptas placeat libero quisquam. Tenetur voluptates in voluptas non aspernatur distinctio placeat repellendus. Aut dignissimos modi distinctio aliquam autem. Doloremque velit quaerat qui aperiam repellendus quis. Iusto ipsa fugit vitae iste natus. Est eos impedit dolores et qui quis non. Id tempora ut rerum ad cum et. Ad voluptatibus enim voluptatem est iste. Quia beatae voluptatem voluptas nihil autem est nobis. Dolore eveniet nesciunt delectus.','https://videotutoriales.com/maspa/maspa2.jpg','https://videotutoriales.com/maspa/maspa2-1.jpg',1,'2017-09-21 16:20:53.000','2017-09-21 16:20:53.000')
,('Eius fuga numquam reprehenderit voluptatem repellendus ut deserunt.','Distinctio voluptatem earum dolores doloribus qui animi. Distinctio voluptates commodi vel quia odio in. Laborum placeat aspernatur dicta facere. Quis in earum reiciendis blanditiis enim ut. Eveniet iusto atque voluptatibus ullam. Et maiores ut veniam cum. Officia eligendi necessitatibus dignissimos provident et enim et. Quam hic in aperiam ut iste debitis laudantium. Qui nihil beatae voluptas laudantium. Delectus possimus quibusdam velit veniam. Quisquam ut ab ea et ut sint hic. Libero perspiciatis odit consequuntur ut. Reiciendis ex explicabo consequatur nihil exercitationem. Eos consequuntur voluptatibus id eius. Quasi enim cupiditate a et accusamus. Fuga quae ea a. Eum tempore et dolor quidem repellat iure dolores. Sapiente dolor mollitia similique excepturi debitis harum. Reprehenderit delectus tempore voluptatum culpa. In dolores modi nihil exercitationem pariatur et cupiditate. Molestiae rerum officia molestiae quia nihil non. Repudiandae doloribus aspernatur perferendis. Perspiciatis omnis enim dicta.','https://videotutoriales.com/maspa/maspa3.jpg','https://videotutoriales.com/maspa/maspa3-1.jpg',4,'2017-09-21 16:20:53.000','2017-09-21 16:20:53.000')
,('Fugiat eos sunt consequatur est eum.','Pariatur cupiditate ut illo ut est. Quia eum vel neque iste fuga. Ipsum itaque dignissimos error itaque facilis. Laudantium rem dolores aut et est perspiciatis. Corporis eius et ab. Neque temporibus maiores unde sit quas. Consequatur provident perspiciatis officia illum esse vitae. Deserunt earum molestiae vel id. Eius voluptas exercitationem accusantium. Fuga est nobis reprehenderit atque. Et vel corrupti sunt mollitia accusantium quos iure voluptas. Et cumque perferendis quia eligendi modi deserunt dolorem quos. Cum qui et eius ipsa cum laborum. Quibusdam veniam qui ab esse. Optio suscipit pariatur repellendus et modi. Deleniti consectetur hic reiciendis aut quia at. In aut repellendus voluptatum dolore perferendis quidem. Natus odio et perspiciatis et nulla neque. Aut necessitatibus nam assumenda at. Officiis esse sit occaecati aut. Vel officia qui temporibus rerum.','https://videotutoriales.com/maspa/maspa5.jpg','https://videotutoriales.com/maspa/maspa5-1.jpg',2,'2017-09-21 16:20:53.000','2017-09-21 16:20:53.000')
,('Aut amet sit sit fugit. Hic eum dolorem est voluptatem rerum ut.','Sed dolor deleniti qui non beatae. Quia facilis dicta est velit. Qui optio deserunt minima qui dolor quia natus. Laudantium totam dolorem aperiam amet ab. A et repudiandae assumenda quia. Aut eos velit ea id et laborum quidem. Totam dicta ut aut corporis distinctio est. Eum et non enim optio. Nesciunt nulla dolor saepe repudiandae quia ut. Nesciunt sint laborum illum qui quis dignissimos. Consequatur eveniet deleniti quisquam fugiat voluptate deleniti. Natus sit consequuntur id eum facilis tempora voluptatem. Autem nostrum et deserunt nemo. Sint rerum ea qui ut quae eius nesciunt est. Repellat similique mollitia nostrum. A quisquam error est. Natus architecto vitae molestias et laborum. Impedit quo a odit molestiae corporis sint. Exercitationem est sed tenetur. Omnis provident laborum id labore. Quia cum dolor suscipit aut. Quis fuga et perferendis est ea maiores.','https://videotutoriales.com/maspa/maspa6.jpg','https://videotutoriales.com/maspa/maspa6-1.jpg',5,'2017-09-21 16:20:53.000','2017-09-21 16:20:53.000')
,('Error sit qui ut quo libero et voluptas.','Iste est excepturi sunt qui error eum. Quidem magnam quidem libero harum ipsum quia. Molestias debitis minima nemo modi aut qui saepe. Voluptatum laboriosam suscipit aperiam doloremque. Facilis qui voluptatem sunt quo ut veritatis voluptas. Magni consequatur voluptate et provident quasi. Cum libero dolor ipsam dignissimos architecto. Magni natus voluptas quis et accusantium. Corrupti animi cupiditate vel velit tempore pariatur. Voluptas sit id aspernatur porro. Soluta placeat pariatur corporis quas adipisci corporis. Animi aut perspiciatis ad natus qui consequatur non cum.','https://videotutoriales.com/maspa/maspa7.jpg','https://videotutoriales.com/maspa/maspa7-1.jpg',1,'2017-09-21 16:20:53.000','2017-09-21 16:20:53.000')
,('Quo aspernatur possimus sequi perferendis.','Eveniet voluptas dolore eum qui. Natus quasi eos placeat quam eos exercitationem. Vero ab consequatur architecto maxime explicabo delectus. Cumque dolor harum et sed odit sunt. Quasi molestiae id vel harum et ut quia. Qui sed similique ad distinctio. Officia error cum earum. Expedita fuga ut est rerum esse. Sunt quia autem optio soluta facilis recusandae totam est. Praesentium exercitationem facere veniam ut. In architecto facere et. Accusantium consequatur qui quidem sint. Et et numquam cupiditate aperiam rerum nihil sit. Est aliquid est et et rerum dolor dolorem. Dicta ut recusandae eum sed. Modi ab quibusdam placeat. Dolor officiis id sit ad eius eaque reiciendis. Culpa ea non velit aliquam. Voluptas dolorem repellat reiciendis tenetur fuga odit suscipit. Ut voluptatem sint cum rerum dolorem laboriosam. Qui voluptatem nihil amet ipsam error. Modi minus est qui et dolores amet.','https://videotutoriales.com/maspa/maspa4.jpg','https://videotutoriales.com/maspa/maspa4-1.jpg',5,'2017-09-21 16:20:53.000','2017-09-21 16:20:53.000')
,('Voluptatem est rerum ex dolorem temporibus omnis ut aut.','Soluta quibusdam sunt aliquam rerum qui adipisci sunt quisquam. Maiores quo nemo laborum assumenda debitis magnam asperiores. Ut nobis eius animi aspernatur et. Unde nobis magni ab sed reprehenderit cupiditate. Et omnis ducimus iure et fugit commodi. Facilis quod omnis nulla aut. Eos quisquam consequatur cum et sint culpa itaque. Voluptas nostrum quasi et. Fuga mollitia natus vitae. Sed et tenetur ea iure sit repellendus. Omnis eos atque possimus ipsum molestiae rem rerum. Tempora dolore perspiciatis vitae voluptatibus quibusdam voluptate veritatis non. Sunt iusto temporibus sed velit error eius eius. Vitae eum dolor sit. Voluptatem sit fuga ducimus veniam consequuntur voluptatem. Dignissimos dolor nostrum nisi est nihil dolorem ut minima. Excepturi et quis veniam. Est voluptatem ipsum eligendi possimus. Quaerat vitae id iste officiis et dolorum. Vitae velit quia hic libero.','https://videotutoriales.com/maspa/maspa8.jpg','https://videotutoriales.com/maspa/maspa8-1.jpg',5,'2017-09-21 16:20:53.000','2017-09-21 16:20:53.000')
;